services:
  fast_api:
    build: .
    container_name: backend
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONPATH=/usr/src/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net

  db:
    image: postgres:17-alpine
    container_name: datamaster_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      start_period: 2s
      start_interval: 3s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - volumes_db:/var/lib/postgresql/data
    networks:
      - net

networks:
  net:

volumes:
  volumes_db:

